[[redirects]]
from = "/*"
to = "/index.html"
status = 200 

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; object-src 'none'; script-src 'self'; style-src 'self'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"